require("jnsw.plugins-setup")
require("jnsw.core.options")
require("jnsw.core.keymaps")
require("jnsw.core.colorscheme")
require("jnsw.plugins.comment")
require("jnsw.plugins.nvim-tree")
require("jnsw.plugins.lualine")
require("jnsw.plugins.telescope")
require("jnsw.plugins.nvim-cmp")
require("jnsw.plugins.lsp.mason")
require("jnsw.plugins.lsp.lspsaga")
require("jnsw.plugins.lsp.lspconfig")
-- require("jnsw.plugins.lsp.null-ls")
require("jnsw.plugins.autopairs")
require("jnsw.plugins.treesitter")
require("neoscroll").setup()
